### ISSUE TITLE
List the members of the batch (read OnbardingBatch contract)

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch4.buidlguidl.com#3]
Show the current members of your batch in the app.

- Show it on the main page or create a page (/builders) listing all the builders registered in the BatchRegistry contract <add here>
- Each builder should link to their personal profile

**Comment by yashgo0018** [comment]
do we have to show the builders who have checked in, or all the builders in the allowlist?

**Comment by JulioMCruz** [comment]
We can create a subgraph to read the CheckedIn event and create a list component with a member component pointing to his profile (eth address) page.

**Comment by vhforbes** [comment]
Isn't this issue closed with the @ryanviana merge? Or there is something that I'm missing?

**Comment by technophile-04** [comment]
> We can create a subgraph to read the CheckedIn event 

100%, but we have nice utility hook in SE-2 [`useScaffoldEvenHistory`](https://docs.scaffoldeth.io/hooks/useScaffoldEventHistory) which does the same obviously subgraph is  the best solution but since the list of events won't be too large I think for our small use case `useScaffoldEvenHistory` works great 🙌

> Isn't this issue closed with the @ryanviana merge? Or there is something that I'm missing?

Ohh yup, closing this as completed in #23
